plugins {
    id 'com.android.application'
}

android {
    namespace 'com.wahshi.cryptoexplosionradar'
    compileSdk 35

    defaultConfig {
        applicationId 'com.wahshi.cryptoexplosionradar'
        minSdk 26
        targetSdk 34
        versionCode 63
        versionName "6.0.2-trace"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
