package com.wahshi.aerofusion;

import android.app.*;import android.os.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import java.io.*;import java.net.*;import java.util.*;import org.json.*;

public class MainActivity extends Activity{
 final int BG=Color.rgb(5,16,27),CARD=Color.rgb(11,31,48),CYAN=Color.rgb(52,214,255),TEXT=Color.rgb(230,247,255),MUTED=Color.rgb(143,174,194),AMBER=Color.rgb(255,179,71);
 EditText from,to; Spinner aircraft; LinearLayout out; ProgressBar progress;
 static class A{String name;double lat,lon;A(String n,double a,double o){name=n;lat=a;lon=o;}}
 final Map<String,A> airports=new HashMap<>();
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);
  airports.put("OOMS",new A("Muscat International",23.5933,58.2844));airports.put("OOSA",new A("Salalah International",17.0387,54.0913));airports.put("OMDB",new A("Dubai International",25.2532,55.3657));airports.put("OMDW",new A("Al Maktoum International",24.8964,55.1614));airports.put("OMAA",new A("Zayed International",24.4330,54.6511));airports.put("OMSJ",new A("Sharjah International",25.3286,55.5172));airports.put("OTHH",new A("Hamad International",25.2731,51.6081));airports.put("OBBI",new A("Bahrain International",26.2708,50.6336));airports.put("OERK",new A("King Khalid International",24.9576,46.6988));airports.put("OEJN",new A("King Abdulaziz International",21.6796,39.1565));
  ScrollView sv=new ScrollView(this);sv.setBackgroundColor(BG);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(32,34,32,60);sv.addView(root);setContentView(sv);
  TextView brand=t("AERO FUSION",28,CYAN,true);root.addView(brand);root.addView(t("FROM ROUTE → TO READY",12,MUTED,true));space(root,22);
  LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);from=input("OOMS");to=input("OMDB");row.addView(box("FROM",from),new LinearLayout.LayoutParams(0,-2,1));space(row,12);row.addView(box("TO",to),new LinearLayout.LayoutParams(0,-2,1));root.addView(row);
  space(root,12);aircraft=new Spinner(this);String[] ac={"E175","E190","A320","B737-8"};ArrayAdapter<String> ad=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,ac);aircraft.setAdapter(ad);root.addView(box("AIRCRAFT",aircraft));
  Button build=new Button(this);build.setText("BUILD MY FLIGHT");build.setTextColor(BG);build.setTextSize(16);build.setTypeface(null,1);GradientDrawable gd=new GradientDrawable();gd.setColor(CYAN);gd.setCornerRadius(22);build.setBackground(gd);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,130);bp.setMargins(0,24,0,18);root.addView(build,bp);
  progress=new ProgressBar(this);progress.setVisibility(View.GONE);root.addView(progress);out=new LinearLayout(this);out.setOrientation(LinearLayout.VERTICAL);root.addView(out);build.setOnClickListener(v->build());build();
 }
 void build(){String f=from.getText().toString().trim().toUpperCase(),d=to.getText().toString().trim().toUpperCase();from.setText(f);to.setText(d);out.removeAllViews();A a=airports.get(f),z=airports.get(d);if(a==null||z==null){card("AIRPORT DATABASE","This APK prototype currently contains the Gulf core airports. AIRAC/global airport resolver is the next connector.",AMBER);return;}double nm=dist(a,z),trk=bearing(a,z);int tas=aircraft.getSelectedItem().toString().startsWith("E17")?420:aircraft.getSelectedItem().toString().startsWith("E19")?430:445;int mins=Math.max(20,(int)Math.round(nm/tas*60+18));
  card(f+"  ✈  "+d,a.name+" → "+z.name+"\n\n"+Math.round(nm)+" NM     "+mins+" MIN     TRACK "+Math.round(trk)+"°\nCRUISE FL350",CYAN);
  card("DATA INTEGRITY","METAR/TAF: LIVE CONNECTOR\nNOTAM: NOT CONNECTED — verify official source\nAIRAC/SID/STAR: NOT CONNECTED — route is great-circle planning only\nSIGMET corridor: NEXT CONNECTOR",AMBER);
  progress.setVisibility(View.VISIBLE);new Thread(()->{String m1=wx("metar",f),m2=wx("metar",d),t1=wx("taf",f),t2=wx("taf",d);runOnUiThread(()->{progress.setVisibility(View.GONE);card("LIVE WEATHER — "+f,(m1+"\n\nTAF\n"+t1),m1.startsWith("Unavailable")?AMBER:CYAN);card("LIVE WEATHER — "+d,(m2+"\n\nTAF\n"+t2),m2.startsWith("Unavailable")?AMBER:CYAN);card("60-SECOND PILOT BRIEF","Route "+f+" to "+d+", "+Math.round(nm)+" nautical miles, initial track "+Math.round(trk)+" degrees. Review the live METAR and TAF above. Verify official NOTAMs, SIGMETs, licensed charts, dispatch data and company procedures before operational use.",Color.rgb(61,224,160));});}).start();
 }
 String wx(String type,String id){HttpURLConnection c=null;try{URL u=new URL("https://aviationweather.gov/api/data/"+type+"?ids="+URLEncoder.encode(id,"UTF-8")+"&format=json");c=(HttpURLConnection)u.openConnection();c.setConnectTimeout(8000);c.setReadTimeout(10000);c.setRequestProperty("Accept","application/json");c.setRequestProperty("User-Agent","AeroFusion/0.2.1 Android");int code=c.getResponseCode();if(code==204)return"No report returned.";if(code!=200)return"Unavailable (HTTP "+code+")";BufferedReader r=new BufferedReader(new InputStreamReader(c.getInputStream()));StringBuilder s=new StringBuilder();String line;while((line=r.readLine())!=null)s.append(line);JSONArray ar=new JSONArray(s.toString());if(ar.length()==0)return"No report returned.";JSONObject o=ar.getJSONObject(0);String raw=type.equals("metar")?o.optString("rawOb",o.optString("raw_text","")):o.optString("rawTAF",o.optString("raw_text",""));return raw.length()>0?raw:"Report received but raw text unavailable.";}catch(Exception e){return"Unavailable — check internet connection and verify through an approved source.";}finally{if(c!=null)c.disconnect();}}
 double dist(A a,A b){double R=3440.065,p1=Math.toRadians(a.lat),p2=Math.toRadians(b.lat),dp=Math.toRadians(b.lat-a.lat),dl=Math.toRadians(b.lon-a.lon);double h=Math.sin(dp/2)*Math.sin(dp/2)+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)*Math.sin(dl/2);return 2*R*Math.asin(Math.sqrt(h));}
 double bearing(A a,A b){double p1=Math.toRadians(a.lat),p2=Math.toRadians(b.lat),dl=Math.toRadians(b.lon-a.lon);double y=Math.sin(dl)*Math.cos(p2),x=Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl);return(Math.toDegrees(Math.atan2(y,x))+360)%360;}
 EditText input(String s){EditText e=new EditText(this);e.setText(s);e.setTextColor(TEXT);e.setTextSize(22);e.setSingleLine(true);e.setBackgroundColor(Color.TRANSPARENT);return e;}
 LinearLayout box(String label,View v){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(22,16,22,16);GradientDrawable g=new GradientDrawable();g.setColor(CARD);g.setCornerRadius(20);g.setStroke(1,Color.rgb(25,63,87));b.setBackground(g);b.addView(t(label,10,MUTED,true));b.addView(v);return b;}
 void card(String title,String body,int accent){space(out,12);LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(24,22,24,22);GradientDrawable g=new GradientDrawable();g.setColor(CARD);g.setCornerRadius(22);g.setStroke(2,accent);b.setBackground(g);b.addView(t(title,15,accent,true));space(b,8);b.addView(t(body,14,TEXT,false));out.addView(b);}
 TextView t(String s,int size,int color,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);if(bold)v.setTypeface(null,1);v.setLineSpacing(0,1.18f);return v;}
 void space(LinearLayout l,int dp){Space s=new Space(this);l.addView(s,new LinearLayout.LayoutParams(dp,dp));}
}