plugins {
    id 'com.android.application'
}

android {
    namespace 'com.wahshi.emb190cbt'
    compileSdk 35

    defaultConfig {
        applicationId 'com.wahshi.emb190cbt'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '2.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }

    packaging {
        resources {
            excludes += ['META-INF/**']
        }
    }
}
